### ISSUE TITLE
Strange borrow check issue

### ISSUE THREAD

**Issue by Andlon** [rustsim/nalgebra#380]
It might be that I'm simply failing to see something blindingly obvious here, but I am having a rather strange issue related to borrow checking. Consider the following very simple function (`nalgebra 0.16.0`): 

```rust
fn modify(y: &mut DVector<f64>) { let slice = y.data.as_mut_slice(); }
```

I get the error:
```
error[E0596]: cannot borrow immutable borrowed content as mutable
 --> src/main.rs:5:47
  |
5 | fn modify(y: &mut DVector<f64>) { let slice = y.data.as_mut_slice(); }
  |                                               ^^^^^^ cannot borrow as mutable

```

I can not for the life of me figure out why this should be problematic. I have a *mutable* reference to a `DVector`, which is essentially just a variant of `Matrix`, which has a field named `data`. I don't see why I cannot borrow this field as mutable. I was unable to reconstruct the problem with standard data structures (`Vec`, slices ...), but I also don't really see how this problem can be specific to `nalgebra`.

I am probably just getting tripped up in some minor detail here. Would appreciate if anyone can point out to me what's going on!

**Comment by sebcrozet** [comment]
First off, note you can just call: `y.as_mut_slice()` here.

Regarding the error you are getting, I think I know what the issue is here. The compiler is probably confused and outputs an error that does not help much. The `.as_mut_slice()` method does exist for `MatrixVec` (which is the type of `y.data`), but it is part of the `StorageMut` trait. Therefore, you need to `use na::storage::StorageMut` to use it. But it appears the compiler does not output the usual error message suggesting to `use` the trait. Why? Well I think this is because `MatrixVec` has a `Deref` impl where `Target` is `Vec`. On the over hand, it does **not** have a `DerefMut` impl. So I think the compiler does the following:

1. Because `StorageMut` has not been `use`, the compiler attempts to deref the `MatrixVec` into a `Vec`.
2. The compiler finds a `.as_mut_slice()` on `Vec` and tries to use it.
3. The compiler figures that, in order to use `.as_mut_slice()`, it needs a mutable ref to the `Vec`.
4. Because no `DerefMut<Target = Vec<N>>` is available for `MatrixVec`, the compiler errors and says it cannot borrow `y.data` as mutable (actually implying it cannot borrow it as a mutable `Vec`).

I think we should just remove the `Deref` impl to avoid this kind of cryptic  errors. Another solution would be to add a `DerefMut` impl, but that's not an option because that would allow the user to `.push/.pop` elements to the vec, which would make the `nrows` and `ncols` fields wrong.
