### ISSUE TITLE
Provide to_homogeneous for MatrixN

### ISSUE THREAD

**Issue by grtlr** [rustsim/nalgebra#471]
There already is a `to_homogeneous` method for `VectorN`, it would be great if nalgebra would provide the same for `MatrixN` (and `SquareMatrix`) to allow homogeneous coordinates in higher dimensions.

Such method would increase the dimensions of `MatrixN` to *N+1* and set `mat[(N,N)] = 1`.

I could try to implement such a method, but right now I am still trying to better understand the structure of nalgebra. @sebcrozet would you be interested in such a method?

**Comment by sebcrozet** [comment]
That would be useful, yes! The implementation and trait bounds would likely look very much like the `.to_homogenous()` method from the `Rotation` type [there](https://github.com/rustsim/nalgebra/blob/master/src/geometry/rotation.rs#L198-L208).

Note however that since there already is a `to_homogeneous` for `VectorN`, you may end up with a duplicated method error (because `VectorN` itself is an alias to a matrix). One way to solve this may be to add the `D: IsNotStaticOne` trait bound where `D` is the dimension type parameter.

**Comment by grtlr** [comment]
Cool! My plan would be to move `to_homogeneous()` from `Rotation` to `MatrixN`. `Rotation` stores a `MatrixN` internally, so then we can just call this method there instead.

As you have predicted, I am running into problems with duplicated method errors. Adding `D: IsNotStaticOne` does not seem to fix this problem. I have added it as a trait bound for the method, and the `impl` block, but still get the errors. Do you have any other ideas on how to solve this problem? Oh and by the way, what is the actual purpose of `IsNotStaticOne`?

**Comment by sebcrozet** [comment]
The `IsNotStaticOne` trait is implemented by `Dynamic` and by all type-level integer except `U1`. So may sometimes be enough to disambiguate situations where other impls of a trait already exist for vectors because vectors are just matrices with a number of columns equal to `U1`.

Would you mind showing what you tried so far so I can try help figuring out how to deal with this? By opening a PR maybe?

**Comment by grtlr** [comment]
I think that I got the disambiguation to work, but now I'm having trouble to get the `Allocator` to work with `DimNameSum`. Here is the PR: #475. Could you maybe take a short look at it? Thank you!
