### ISSUE TITLE
Inverse of identity matrix does not result in identity

### ISSUE THREAD

**Issue by djozis** [rustsim/nalgebra#476]
Using nalgebra 0.16.10 and Rust nightly.

I'm new to Rust and nalgebra (so pardon me if this is just me being a novice) but I would have expected `nalgebra::Matrix3::<f32>::identity().inverse()` to result in the identity matrix, but instead it results in `[-1.0, -0.0, -0.0, -0.0, -1.0, -0.0, -0.0, -0.0, -1.0]`. I suspect this is additive inverse vs multiplicative inverse, but as a relatively new nalgebra/Rust user, I found this unintuitive and it caught me by surprise.

`nalgebra::Matrix3::<f32>::identity().try_inverse().unwrap()` produces `[1.0, -0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]`, which is as I expected.

**Comment by sebcrozet** [comment]
You are right, `.inverse()` will return the additive inverse (and comes from the `alga` traits) while `.try_inverse()` is really what you'd expect. This confusion is a known issue and will be fixed by https://github.com/rustsim/alga/pull/54. Because this is a breaking change we are still waiting a bit before merging it.

**Comment by djozis** [comment]
Thanks for clarifying!

**Comment by sebcrozet** [comment]
Closing this as this will be fixed in today's release of alga.
