### ISSUE TITLE
Cannot use glm::radians(f32 or f64)

### ISSUE THREAD

**Issue by Thomspoon** [rustsim/nalgebra#636]
I hope I'm not misunderstanding how to use this function, but if it's meant to be 1:1 with GLM, shouldn't this function be able to be called with a raw f32 or f64? Currently I am unable to call it because of the following compiler error:

```
error[E0308]: mismatched types
   --> src/main.rs:150:62
    |
150 |             model = glm::rotate(&model, ticks * glm::radians(20.0), &glm::vec3(1.0, 0.3, 0.5));
    |                                                              ^^^^ expected reference, found floating-point number
    |
    = note: expected type `&nalgebra::base::matrix::Matrix<_, _, nalgebra::base::dimension::U1, _>`
               found type `{float}`
```
Is there a trait missing that coerces an f32 or &f32 into a Matrix<_, _, U1, _>?

**Comment by sebcrozet** [comment]
Because Rust does not allow overloading, `nalgebra-glm` is not strictly 1:1 with GLM. In particular, the method you mentioned only works on vectors.

We did not add a scalar equivalent but note that the [.to_radians](https://doc.rust-lang.org/std/primitive.f64.html#method.to_radians) method already exists for the `f32` and `f64` types. So you can simply do:

```rust
model = glm::rotate(&model, ticks * f64::to_radians(20.0), &glm::vec3(1.0, 0.3, 0.5));
```

**Comment by Thomspoon** [comment]
Ah, I understand the issue/non-issue now. Thank you for explaining this.
