### ISSUE TITLE
Slerp for Vectors yields innacurate result

### ISSUE THREAD

**Issue by cedric-h** [rustsim/nalgebra#685]
Minimal Reproduction: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3bc7aa3fef5229d83b758d9c5c610e37

**Comment by sebcrozet** [comment]
This is related to https://github.com/rustsim/nalgebra/pull/568 which was about fixing slerp between quaternions with a negative dot product.

The bug here happens between any pair of vectors with negative dot-products.

This is interesting because this problem of flipped sign is a non-issue with quaternions because of their double-covering nature (i.e. the unit quaternion `q` represents the same rotation as its opposite `-q`). Of course, regular vectors on the other hand don't have this double-covering property.

**Comment by sebcrozet** [comment]
I think the fix is to revert #568, and make a special-case for quaternion to take their double-covering nature into account.
