### ISSUE TITLE
new_translation, transform_vector am i missing someting

### ISSUE THREAD

**Issue by rakita** [rustsim/nalgebra#694]
Hello guys, I need some clarification on usage of transform_vector. I want to create a transformation matrix and then transform vector and it seems that transformation is ignored. Here is code:

```
extern crate nalgebra_glm as glm;

fn main() {
    let mat = glm::Mat3::new_translation(&glm::Vec2::new(10.0,20.0));
    let vec = glm::Vec2::new(1.0,1.0);
    let vec_trans = mat.transform_vector(&vec);
    println!("Vec: {:?}", vec_trans);

}
```

What am I missing here?

**Comment by sebcrozet** [comment]
Hi! Within nalgebra, there is a semantic difference between a _point_ and a _vector_. A point is affected by translations while a vector is not. That's why nothing happens in your example.

In order to perform your transformation using vectors, you will need to use a 3D vector with a `1.0` at the end of the vector: `let v = glm::Vec3::new(1.0, 1.0, 1.0);` and transform it `let vec_trans = mat * vec;`. This is the way it is expected to be done with glm (which is inspired from glsl).

Your other alternative is to use points, but those are not part of `nalgebra_glm` (they are part of nalgebra itself):

```rust
let pt = Point2::new(1.0, 1.0);
let pt_trans = mat.transform_point(&pt);
```

**Comment by rakita** [comment]
Oh, I get your point (pun intended :)). It is a nice distinction between _points_/_vectors_
ty sebcrozet
