### ISSUE TITLE
Generic scalar-vector multiplication does not work when scalar is on the left side

### ISSUE THREAD

**Issue by nnmm** [rustsim/nalgebra#718]
It seems that multiplication of a generic `Vector3<N>` with a scalar works only when the scalar is on the right side: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=09a88e811c41641c758077cc8c87a067
Trying to do so results in two `mismatched types` errors. I also reproduced it with version 0.21.0, same problem.

I hope this is not a duplicate or user error. Thanks for the great library!

**Comment by sebcrozet** [comment]
Hi!

Yes, this is a common limitation with rust trait system. Making this work with the scalar on the left-on-side would require us to write an impl like that:

```rust
impl<N> Mul<Vector3<N>> for N {
    ...
}
```

But this kind of blanket impl is not allowed by Rust orphan rules because `Mul` is not a trait defined by nalgebra. The only way around this is to impl for specific scalar types:

```rust
impl Mul<Vector3<f32>> for f32 {
   ...
}
```

But as you noticed, this cannot work in generic code.

When specialization will be supported in Rust, I guess, this will become possible. But until then scalars in the left-hand-side on generic code is not implementable.

**Comment by nnmm** [comment]
That makes sense, thanks. Feel free to close this ticket.

**Comment by filnet** [comment]
Had the same issue...
Here is [left_scalar_mul_impl](https://github.com/rustsim/nalgebra/blob/66957980ccb544da2cb585aaffd5b256917d047b/src/base/ops.rs#L525) which is used to implement lhs mul for these scalar types: 

```left_scalar_mul_impl!(u8, u16, u32, u64, usize, i8, i16, i32, i64, isize, f32, f64);```
