### ISSUE TITLE
Loss of precision when converting UnitQuaternion<f32> to Rotation3<f32> matrix

### ISSUE THREAD

**Issue by FelixBrakel** [rustsim/nalgebra#721]
```rust
struct Transform {
    rotation: UnitQuaternion<f32>,
    other_rotation: Rotation3<f32>
}

impl Transform {
    pub fn rotate(&mut self, x: f32, y: f32, z: f32) {
        let curr_rot = self.rotation.to_rotation_matrix();

        let x_axis = Vector3::x_axis();
        let y_axis = Vector3::y_axis();
        let z_axis = Vector3::z_axis();

        let x_rot = Rotation3::from_axis_angle(&x_axis, x);
        let y_rot = Rotation3::from_axis_angle(&y_axis, y);
        let z_rot = Rotation3::from_axis_angle(&z_axis, z);

        assert_relative_eq!(curr_rot, self.other_rotation, epsilon = 1.0e-4);

        self.other_rotation = curr_rot * z_rot * y_rot * x_rot;
        self.rotation = UnitQuaternion::from_rotation_matrix(&self.other_rotation);
    }
}
```

This panics after a couple iterations of calling `rotate(0., 0.01, 0.)`.

Looking at the panic it seems that the elements in the matrix causing the `assert_relative_eq` to fail are always the first and the last one.

Looking at the source code:
```rust
    pub fn to_rotation_matrix(&self) -> Rotation<N, U3> {
        let i = self.as_ref()[0];
        let j = self.as_ref()[1];
        let k = self.as_ref()[2];
        let w = self.as_ref()[3];

        let ww = w * w;
        let ii = i * i;
        let jj = j * j;
        let kk = k * k;
        let ij = i * j * crate::convert(2.0f64);
        let wk = w * k * crate::convert(2.0f64);
        let wj = w * j * crate::convert(2.0f64);
        let ik = i * k * crate::convert(2.0f64);
        let jk = j * k * crate::convert(2.0f64);
        let wi = w * i * crate::convert(2.0f64);

        Rotation::from_matrix_unchecked(Matrix3::new(
            ww + ii - jj - kk,
            ij - wk,
            wj + ik,
            wk + ij,
            ww - ii + jj - kk,
            jk - wi,
            ik - wj,
            wi + jk,
            ww - ii - jj + kk,
        ))
    }
```

It seems that `ww`, `ii`, `jj` and `kk` maybe aren't converted correctly?

**Comment by sebcrozet** [comment]
Hi!

Running this on the [rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4e196616f091890c8ea3463cedfbb6ac) I can reproduce the panic after about 200 iterations. I believe this is caused by the accumulation of rounding errors due to the accumulated multiplications, and conversions between matrices and quaternions (the matrix -> quaternion conversion in particular involves a square root and divisions).

Looking at the norm of the quaternion, we can see that it drifts from 1 progressively because of those accumulated rounding errors, and reaches `0.9999031` before the panic.

The typical solution for this is to renormalize the quaternion from time to time in order to avoid the accumulation of errors. For example adding `self.rotation.renormalize_fast()` in the `rotate` method will do the trick (though you likely don't need to do it every single time). Note that the `renormalize_fast` [method](https://www.nalgebra.org/rustdoc/src/nalgebra/base/unit.rs.html#135-140) is based on first-order Taylor approximation, so it is pretty fast and works well for almost-normalized values.

**Comment by FelixBrakel** [comment]
Hey!

Thank you for pointing me to the `renormalize_fast` method! I ended up just multiplying quaternions directly which mitigates the problem so I can call the `renormalize` even less frequently.
