### ISSUE TITLE
Problem with core dumped

### ISSUE THREAD

**Issue by ManuelCostanzo** [rustsim/nalgebra#732]
Hello ! I have a problem: I need a 1024x1024 matrix (until 16364x16384) but with this code:

```
use typenum::U1024 as N;
type NxNMatrix = MatrixN<f32, N>;

fn main() {
    let graph = NxNMatrix::zeros();
    println!("{}", graph[(0, 0)]);
}

```
My program crashes with:

> thread 'main' has overflowed its stack
> fatal runtime error: stack overflow
> ./run.sh: line 15: 15382 Aborted                 (core dumped)

I have 12GB RAM. How can i solve this ? Thank you !

**Comment by sebcrozet** [comment]
Hi!

This has been answered on rust's user forum: https://users.rust-lang.org/t/how-to-create-a-nxn-matrix-in-nalgebra/43037/10

**tl;dr** - you need to use a dynamically-sized matrix `DMatrix::zeros(1024, 1024)` instead of a statically-sized matrix. The former will be heap-allocated while the latter is stack-allocated (hence the stack overflow).

**Comment by sebcrozet** [comment]
I'm closing this since the answer was given above. Feel free to reopen if you have an issue with this solution.
