### ISSUE TITLE
Implement NamedDim for all typenums

### ISSUE THREAD

**Issue by orf** [rustsim/nalgebra#739]
For sizes less or equal to 127 you need to use `nalgebra:dimension:U*` dimensions, and greater than 128 you need to use `typenum` enums.

This makes sense. However if you're building a library that uses `nalgebra` as an implementation detail and you want to allow consumers to be able to specify a dimension, you have to leak nalgebra to the consumer. For example:

```rust
pub struct Map<DimX>
where
    DimX: DimName,
    DefaultAllocator: Allocator<WideF32x4, DimX>,
{
    points: Vec<Point32<DimX>>,
}
```

Ideally a consumer of this `Map` struct is shielded from the fact it uses `nalgebra` at all, and they can configure the dimensions with `typenum`. But if they want to use a dimension less than 128 they need to use `nalgebra` directly, which leaks an implementation detail to the consumers :(

So is it possible to implement `DimName` for all `typenum` variants [here](
https://github.com/rustsim/nalgebra/blob/b81aed767f15c9f278e78b1f1a5920aab57a6add/src/base/dimension.rs#L301)? This way they can always use `typenum` and not know about `nalgebra`.

**Comment by sebcrozet** [comment]
I don't think that is possible without introducing significant confusion. In particular that would imply that:
- A `Vector<f32, nalgebra::U3>` would not be considered the same as a `Vector<f32, typenum::U3>` which is confusing.
- All methods implemented specifically for low-dimensional vectors/matrices won't be useable because they are implemented for, e.g., `impl<N> Vector<N, nalgebra::U3>`.
- Geometric type will likely not work either because they use nalgebra's U2/U3/U4 explicitly.

One alternative you could try though is to use the `NamedDim` constraint instead of `DimName`:

```rust
pub struct Map<DimX>
where
    DimX: NamedDim,
    DefaultAllocator: Allocator<WideF32x4, DimX::Name>,
{
    points: Vec<Point32<DimX::Name>>,
}
```

The `NamedDim` trait is implemented by all typenum types, and allows nalgebra to deduce the corresponding nalgebra dimension type.

**Comment by orf** [comment]
Using `NamedDim` is perfect. Thank you so much @sebcrozet, and thanks for this amazing library ❤️.
